SELECT TO_CHAR(VISITED_ON,'YYYY-MM-DD') AS VISITED_ON,AMOUNT,AVERAGE_AMOUNT
FROM (
	SELECT VISITED_ON,
	SUM(AMOUNT) OVER (ORDER BY VISITED_ON ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS AMOUNT,
	ROUND(AVG(AMOUNT) OVER (ORDER BY VISITED_ON ROWS BETWEEN 6 PRECEDING AND CURRENT ROW),2) AS      AVERAGE_AMOUNT,
	DENSE_RANK() OVER (ORDER BY VISITED_ON) AS DAY_CNT
	FROM 
		(SELECT VISITED_ON, SUM(AMOUNT) AS AMOUNT
		FROM
		CUSTOMER
		GROUP BY VISITED_ON) 
		)
WHERE DAY_CNT >= 7
ORDER BY VISITED_ON